# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - python-tornado
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython
    
    
language: python
python: 3.6


env:
    - OMV_ENGINE=Brian2

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    #- pip install scipy # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
    
 

script:
    - omv all -V
    - omv list-engines -V
    
    
    

